---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by arciesis.
--- DateTime: 2/22/24 5:18 PM
---
--- @module PalDpsMeter.otomoUniqueId
local otomoUniqueId = {}

--- Represent an unique id for otomo, it's actually the address of a ScriptStruct: PalInstanceId
---@class OtomoUniqueId
---@field Addr number
local OtomoUniqueId = {}

--- getter of the structAddr property
---@return number theStructAddr
function OtomoUniqueId:getAddr()
   return self.Addr
end

--- internal tostring method
---@return string str
---@private
function OtomoUniqueId:__tostring()
   return string.format("OtomoUnique Identifier: %i", self:getAddr())
end

--- ToString method
---@return string str the string representing the data
function OtomoUniqueId:ToString()
   return self:__tostring()
end

--- Test if two Instances of this class are isEqual
---@param otherUId OtomoUniqueId
---@return boolean bool true if there are equal and false otherwise
function OtomoUniqueId:isEqual(otherUId)
   if self:getAddr() == 0 or otherUId:getAddr() == 0 then
      return false
   end

   return (self:getAddr() == otherUId:getAddr())
end

--- Constructor of a PalInstanceID
--- @param structAddr number
function otomoUniqueId.new(structAddr)
   local self = {}
   setmetatable(self, { __index = OtomoUniqueId })

   self.Addr = structAddr

   return self
end

return otomoUniqueId