---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by arciesis.
--- DateTime: 2/22/24 5:18 PM
---
--- @module PalDpsMeter.otomoUniqueId
local otomo_unique_id = {}

--- Represent an unique id for otomo, it's actually the address of a ScriptStruct: PalInstanceId
---@class OtomoUniqueId
---@field otomo_addr number
local OtomoUniqueId = {}

--- getter of the structAddr property
---@return number theStructAddr
function OtomoUniqueId:get_addr()
   return self.otomo_addr
end

--- internal tostring method
---@return string str
---@private
function OtomoUniqueId:__tostring()
   return string.format("OtomoUnique Identifier: %i", self:get_addr())
end

--- ToString method
---@return string str the string representing the data
function OtomoUniqueId:ToString()
   return self:__tostring()
end

--- Test if two Instances of this class are isEqual
---@param other_unique_id OtomoUniqueId
---@return boolean true if there are equal and false otherwise
function OtomoUniqueId:is_equal(other_unique_id)
   if self:get_addr() == 0 or other_unique_id:get_addr() == 0 then
      return false
   end

   return (self:get_addr() == other_unique_id:get_addr())
end

--- Constructor of a PalInstanceID
--- @param struct_addr number
function otomo_unique_id.new(struct_addr)
   local self = {}
   setmetatable(self, { __index = OtomoUniqueId })

   self.Addr = struct_addr

   return self
end

return otomo_unique_id